name: CMake - Linux-Makefile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build and test release build
  Release:
    env:
      BUILD_TYPE: Release
    runs-on: ubuntu-latest

    steps:
    - name: Install NASM
      run: sudo apt-get install -y nasm

    - uses: actions/checkout@v3
      with:
        repository: 'intel/intel-ipsec-mb'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -j 5 -C ${{env.BUILD_TYPE}}

    - name: Install
      working-directory: ${{github.workspace}}/build
      run: sudo cmake --install .

    - name: Test installation
      working-directory: ${{github.workspace}}/examples/burst-app
      run: gcc main.c -lIPSec_MB

  Debug:
    # Build and test debug build
    env:
      BUILD_TYPE: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Install NASM
      run: sudo apt-get install -y nasm
  
    - uses: actions/checkout@v3
      with:
        repository: 'intel/intel-ipsec-mb'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -j 5 -C ${{env.BUILD_TYPE}}
