name: Linux Build Shared gcc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install -y nasm
    - uses: actions/checkout@v3
      with:
        repository: intel/intel-ipsec-mb
    - name: make
      run: make -j
